### ISSUE TITLE
Round-tripping fails when freezeThreshold is set

### ISSUE THREAD

**Issue by tomjack** [bigmlcom/histogram#58]
I ran into this problem while writing tests for my own serialization code. Luckily, I don't think I actually need freezeThreshold right now.

So far, I just have [a failing test](https://github.com/tomjack/histogram/compare/round-trip-frozen).

Seems like there are two different errors:

1. IndexOutOfBounds, I'm guessing when the freeze threshold is exceeded on the first bin. Don't understand this one fully yet.
2. Bins mismatch after round-trip. If we want to round-trip with insert-bin!, seems like we need some flag for "insert, but ignore freezeThreshold for this insert". Otherwise lots of bins at the end get squashed into one bin as soon as the freezeThreshold is exceeded.

Also, note that the existing round trip test makes no assertions :).

**Comment by ashenfad** [comment]
Your fix looked good.  I cherry-picked your change as part of #59.  Thanks!
