### ISSUE TITLE
Ways to freeze bins and re-process data?

### ISSUE THREAD

**Issue by arnaudsj** [bigmlcom/histogram#61]
Hi,

First of all, great job on this lib. I totally love it! I have a question though on how this can be used to properly capture the distribution of multiple samples while preserving the bins location.

At the moment, all I see possible is to merge all the histograms from each sample into one, then freeze the bins, and somehow clear the histogram while keeping the frozen bins, and then re-add each sample one by one to have a fixed bin placement across all samples.

Is there any better way to do this? Is there another approach I should be aware of for this particular case?

Thank you in advance!

**Comment by ashenfad** [comment]
I'm not sure why you want to preserve the bin locations for each histogram / sample.  Are you looking to build a traditional histogram with fixed bins?  Assuming you're okay with two passes over the data, then you could start as you suggested by merging the streaming histograms.  Then you could use `uniform` to choose the bin edges for a traditional histogram and make a second pass over the data.

```clojure
(uniform (merge! hist1 hist2) 4)
```

But perhaps I'm missing something?

**Comment by arnaudsj** [comment]
Thank you @ashenfad, I am looking at trying to get the best possible bin placement to approximate the distribution of multiple similar but noisy samples, so I don't quite want the regular fixed spaced bins.

I would like to be able to merge all the histograms into one, extract the bins placement, then reprocess each sample to fit and populate N histograms against the fixed (frozen) bins I got when merging all the histograms of each samples. The end goal being to be able to use the N histograms as vectors for a ML classifier.

I hope it makes sense. Maybe I am not using the lib as intended. Let me know!

**Comment by charleslparker** [comment]
I just wanted to give a +1 for this idea.  It would be nice in areas like computer vision, where we're constantly "histogramming" the pixels in a single image to get feature vectors.  A natural workflow would be construct a histogram from the training pixels for all images to get the bin edges, "empty out" the bins, freeze the edges, then run an individual image's pixels through the histogram to get the feature vector for that image.  Of course you'd have to "re-empty" for each image in training and test.

I've had to hack appropriate bin edges for lots of problems of this type in the past; it's surprising how often "uniformly spaced between 0 and 255" doesn't work.  This would have been really nice to have.

It seems like all we'd need to make this work is something like an `empty` function if that's not already around.

**Comment by ashenfad** [comment]
The `uniform` function returns edges for bins with equal population (not equal space).  If I were to discretize a distribution, I'd expect `uniform` to give better results than using the raw bins from the streaming histogram.  The raw bins will often capture low-density areas, so the bin populations can vary wildly.  Then again, maybe capturing some outliers in the feature vector is useful.

Anyway, @arnaudsj, this fn hopefully does what you're looking for.  It takes a histogram (the merged histogram in your case) and returns a "cleared" and "frozen" version of the original.  Let me know if it's useful, I might add it to a future release.

```clojure
(defn clear-freeze
  "Returns a frozen histogram whose bin locations match the given
   histogram."
  [hist]
  (let [bs (bins hist)]
    (reduce insert-bin!
            (create :bins (count bs) :freeze 0)
            (map #(assoc % :count 0) bs))))
```

**Comment by arnaudsj** [comment]
@ashenfad perfect! The function you provided seems to do the trick! Let me see if it provides now the results I expected ;)

Thank you so much for your help!

**Comment by charleslparker** [comment]
> The raw bins will often capture low-density areas, so the bin populations can vary wildly. Then again, maybe capturing some outliers in the feature vector is useful.

Right - I'm thinking specifically of images that are high-frequency filtered.  The vast majority of the pixels will be near zero-valued, but a small subset (the edges) represent the interesting areas of the distribution.
